<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>ComTam.ConsoleHarness</RootNamespace>
    <AssemblyName>ComTam.ConsoleHarness</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ComTam.Core/ComTam.Core.csproj" />
  </ItemGroup>

</Project>
